In [31]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation,Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy
from random import randint
import numpy as np
from random import shuffle
from sklearn.preprocessing import MinMaxScaler

In [23]:
test_labels=[]
test_samples=[]

train_labels=[]
train_samples=[]

In [25]:
#test
for i in range(10):
    random_younger=randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(1)
    #the 5% of older indivisuals who didnot experience side effects
    random_older=randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)

for i in range(200):
    random_younger=randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(0)
    #the 5% of older indivisuals who didnot experience side effects
    random_older=randint(65,100)
    test_samples.append(random_older)
    test_labels.append(1)

#train   
for i in range(10):
    random_younger=randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)
    #the 5% of older indivisuals who didnot experience side effects
    random_older=randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)

for i in range(200):
    random_younger=randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)
    #the 5% of older indivisuals who didnot experience side effects
    random_older=randint(65,100)
    train_samples.append(random_older)
    train_labels.append(1)

In [30]:
train_labels=np.array(train_labels)
test_labels=np.array(test_labels)

train_samples=np.array(train_samples)
test_samples=np.array(test_samples)

# train_labels,train_samples=shuffle(train_labels,train_samples)

In [33]:
scaler=MinMaxScaler()
scaled_train_sample=scaler.fit_transform(train_samples.reshape(-1,1))

In [34]:
physical_devices=tf.config.experimental.list_physical_devices("GPU")
print("Number of GPU available",len(physical_devices))
# tf.config.experimental.set_memory_growth(physical_devices[0],True)

Number of GPU available 0


In [35]:
model=Sequential([
    Dense(units=16,input_shape=(1,),activation="relu"),
    Dense(units=32,activation="relu"),
    Dense(units=2,activation="softmax")
])

In [36]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 16)                32        
                                                                 
 dense_4 (Dense)             (None, 32)                544       
                                                                 
 dense_5 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.compile(optimizer=Adam(learning_rate=0.0001),loss="sparse_categorical_crossentropy",metrics=["accuracy"])

In [43]:
model.fit(x=scaled_train_sample,y=train_labels,batch_size=10,epochs=30,shuffle=True,verbose=2)

Epoch 1/30
84/84 - 0s - loss: 0.4206 - accuracy: 0.8893 - 195ms/epoch - 2ms/step
Epoch 2/30
84/84 - 0s - loss: 0.4115 - accuracy: 0.8917 - 189ms/epoch - 2ms/step
Epoch 3/30
84/84 - 0s - loss: 0.4029 - accuracy: 0.8917 - 194ms/epoch - 2ms/step
Epoch 4/30
84/84 - 0s - loss: 0.3945 - accuracy: 0.8964 - 195ms/epoch - 2ms/step
Epoch 5/30
84/84 - 0s - loss: 0.3865 - accuracy: 0.8964 - 224ms/epoch - 3ms/step
Epoch 6/30
84/84 - 0s - loss: 0.3790 - accuracy: 0.8976 - 153ms/epoch - 2ms/step
Epoch 7/30
84/84 - 0s - loss: 0.3720 - accuracy: 0.9024 - 228ms/epoch - 3ms/step
Epoch 8/30
84/84 - 0s - loss: 0.3651 - accuracy: 0.9131 - 178ms/epoch - 2ms/step
Epoch 9/30
84/84 - 0s - loss: 0.3588 - accuracy: 0.9155 - 202ms/epoch - 2ms/step
Epoch 10/30
84/84 - 0s - loss: 0.3528 - accuracy: 0.9119 - 221ms/epoch - 3ms/step
Epoch 11/30
84/84 - 0s - loss: 0.3471 - accuracy: 0.9167 - 184ms/epoch - 2ms/step
Epoch 12/30
84/84 - 0s - loss: 0.3416 - accuracy: 0.9167 - 201ms/epoch - 2ms/step
Epoch 13/30
84/84 - 0s - 

In [45]:
test_labels[:10]

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [48]:
test_samples[:10]

array([59, 90, 19, 91, 32, 87, 34, 71, 55, 95])

In [55]:
scaled_test_samples=scaler.fit_transform(test_samples.reshape(-1,1))

In [56]:
scaled_test_samples[:10]

array([[0.52873563],
       [0.88505747],
       [0.06896552],
       [0.89655172],
       [0.2183908 ],
       [0.85057471],
       [0.24137931],
       [0.66666667],
       [0.48275862],
       [0.94252874]])

In [59]:
predictions=model.predict(x=scaled_test_samples,batch_size=10,verbose=1)

84/84 [==============================] - 0s 2ms/step


In [78]:
import pandas as pd
data=[]
for i in predictions:
    data.append(i)
rouded_prediction=np.argmax(data,axis=1)
rouded_prediction[:10]

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64)

In [82]:
data=pd.DataFrame(rouded_prediction)
data.columns=["No sideeffect-0 side-effect-1"]
data

No sideeffect-0 side-effect-1
0                                0
1                                1
2                                0
3                                1
4                                0
..                             ...
835                              1
836                              0
837                              1
838                              0
839                              1

[840 rows x 1 columns]

In [83]:
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt

In [84]:
cm=confusion_matrix(test_labels,data)
cm

array([[378,  42],
       [ 20, 400]], dtype=int64)

In [85]:
model.save("model_ANN.h5")

In [90]:
new_model=tf.keras.models.load_model("model_ANN.h5")

In [91]:
new_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 16)                32        
                                                                 
 dense_4 (Dense)             (None, 32)                544       
                                                                 
 dense_5 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [93]:
new_model.get_weights()

[array([[-0.34753388, -0.0636487 , -0.05085206, -0.27627534, -0.03708988,
          0.26212853,  0.30754185, -0.19937563, -0.3399579 , -0.59086746,
         -0.10424989, -0.41664332, -0.40137053,  0.65642023, -0.01833791,
         -0.5625322 ]], dtype=float32),
 array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -0.0007632 , -0.07492477,  0.17462187,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        , -0.083587  ,  0.        ,
         0.        ], dtype=float32),
 array([[ 3.11071128e-01, -2.78314263e-01,  1.77102238e-01,
          2.20243663e-01,  3.22945982e-01,  3.46935481e-01,
         -9.12007987e-02, -1.43536031e-02, -2.23286331e-01,
         -2.43079156e-01, -1.62301108e-01, -2.64636010e-01,
          2.52559274e-01,  3.06098491e-01, -1.59889624e-01,
         -1.78153798e-01, -2.46211261e-01, -4.34812903e-03,
         -1.27933323e-02,  5.25504649e-02,  3.35691273e-02,
         -3.07295442e-01, -7.42248893e-02, -2.33482838e-01,
 

In [96]:
new_model.optimizer

In [97]:
json_string=model.to_json()

In [98]:
json_string

'{"class_name": "Sequential", "config": {"name": "sequential_1", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 1], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_3_input"}}, {"class_name": "Dense", "config": {"name": "dense_3", "trainable": true, "batch_input_shape": [null, 1], "dtype": "float32", "units": 16, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_4", "trainable": true, "dtype": "float32", "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "

In [99]:
model.save_weights("model_ANN_weights.h5")

In [100]:
model2=Sequential([
    Dense(units=16,input_shape=(1,),activation="relu"),
    Dense(units=32,activation="relu"),
    Dense(units=2,activation="softmax")
])

In [101]:
model2.load_weights("model_ANN_weights.h5")

In [103]:
model2.get_weights()

[array([[-0.34753388, -0.0636487 , -0.05085206, -0.27627534, -0.03708988,
          0.26212853,  0.30754185, -0.19937563, -0.3399579 , -0.59086746,
         -0.10424989, -0.41664332, -0.40137053,  0.65642023, -0.01833791,
         -0.5625322 ]], dtype=float32),
 array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -0.0007632 , -0.07492477,  0.17462187,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        , -0.083587  ,  0.        ,
         0.        ], dtype=float32),
 array([[ 3.11071128e-01, -2.78314263e-01,  1.77102238e-01,
          2.20243663e-01,  3.22945982e-01,  3.46935481e-01,
         -9.12007987e-02, -1.43536031e-02, -2.23286331e-01,
         -2.43079156e-01, -1.62301108e-01, -2.64636010e-01,
          2.52559274e-01,  3.06098491e-01, -1.59889624e-01,
         -1.78153798e-01, -2.46211261e-01, -4.34812903e-03,
         -1.27933323e-02,  5.25504649e-02,  3.35691273e-02,
         -3.07295442e-01, -7.42248893e-02, -2.33482838e-01,
 

In [ ]:
#END THIS IS THE COMPLETE LECTURE FOR ANN CODE